Поменял aside на navbar, изменил цвета на темные
MrFang/budget-manager pull request #15
Opened 2020-10-08 18:16 UTC by PitKoro

Изменил дизайн. Посмотрите, может так лучше.

2020-10-08 19:16 UTC, MrFang commented
Сделай, плз меню вертикальным. У нас пробелма с местом по краям а не сверху

2020-10-08 19:17 UTC, MrFang commented
И куда вы дели элемент .container? Он же нормально работал

2020-10-08 19:23 UTC, MrFang commented on core/templates/core/base.html
> +          <a class="nav-link {% if url_name == 'main' %}active{% endif %}" href="{% url 'main' %}"><i class="fas fa-home"> Главная страница</i></a>
Зачем весь текст в i? Вполне можно сделать span для иконки и рядом текст (или span для текста)

2020-10-08 22:21 UTC, PitKoro commented on core/templates/core/base.html
> +          <a class="nav-link {% if url_name == 'main' %}active{% endif %}" href="{% url 'main' %}"><i class="fas fa-home"> Главная страница</i></a>
бутстрапу нужно так

2020-10-08 22:22 UTC, PitKoro commented
> И куда вы дели элемент .container? Он же нормально работал

Не видел такого

2020-10-09 06:13 UTC, MrFang commented
> > И куда вы дели элемент .container? Он же нормально работал
> 
> Не видел такого

Ты в этом реквесте снёс `.conteiner-body`. Он почему-то возник на месте `.container` после Серёжиных изменений

2020-10-09 06:16 UTC, MrFang commented on core/templates/core/base.html
> +          <a class="nav-link {% if url_name == 'main' %}active{% endif %}" href="{% url 'main' %}"><i class="fas fa-home"> Главная страница</i></a>
Можно ссылку на документацию?

2020-10-09 21:25 UTC, PitKoro commented on core/templates/core/base.html
> +          <a class="nav-link {% if url_name == 'main' %}active{% endif %}" href="{% url 'main' %}"><i class="fas fa-home"> Главная страница</i></a>
Ему так не нужно...

2020-10-10 07:48 UTC, MrFang requested changes

2020-10-10 07:48 UTC, MrFang commented on core/templates/core/base.html
> +        <div class="col-10">
Можно просто `.col`. Максимальное кол-во колонок 12, он автоматически посчитает

2020-10-10 07:48 UTC, MrFang commented on core/static/css/core.css
> +  color: #fff;
Если честно, я не вижу разницы между цветами активной и неактивной ссылки. Может тогда с ними не запариваться?

2020-10-10 07:48 UTC, MrFang commented on core/templates/core/base.html
> +    <div class="conteiner">
Почему вы оба делаете одну и ту же опечатку в слове container? Напиши нормально или даже container-fluid из-за тёмной темы. И тогда уже смотри, какие стили надо фиксить у тебя грид нормально заработает

2020-10-10 07:48 UTC, MrFang commented on core/templates/core/base.html
> +                <img src="{% static 'img/main_logo.png' %}" width="80px" height="30px" alt="" loading="lazy">
Стили в css. Сделай класс лого и унеси их туда

2020-10-10 07:48 UTC, MrFang commented on core/static/css/core.css
>  aside {
Вообще не уверен, что нам нужен этот тег, но если хотите, ок

2020-10-10 07:48 UTC, MrFang commented on core/templates/core/base.html
> +            <nav class="nav">
Используй navbar Там есть встроенная поддержка лого

2020-10-10 07:52 UTC, MrFang commented
Я тут подумал. Идея с тёмной темой хорошая и реализована не плохо, но может нам откатить? Во-первых, весь остальной веб по-умолчанию, предполагает светлую и с этим есть определённый геморрой, во-вторых, нормальные люди (не программисты) не часто используют dark-mode, не всем удобно.
Если кто-то хочет заморочиться, можно в качестве факультатива сделать переключатель тем. Это не самая простая для нас задача

2020-10-10 09:26 UTC, PitKoro commented on core/static/css/core.css
>  aside {
Какой тег то?

2020-10-10 09:27 UTC, PitKoro commented on core/templates/core/base.html
> +            <nav class="nav">
navbar для меню сверху

2020-10-10 09:28 UTC, MrFang commented on core/static/css/core.css
>  aside {
aside

2020-10-10 09:30 UTC, PitKoro commented on core/static/css/core.css
> +  color: #fff;
Разница есть, но небольшая

2020-10-10 09:34 UTC, MrFang commented on core/templates/core/base.html
> +            <nav class="nav">
О! Я понял. Читайте доку. Чтобы сделать вектикальное меню нужно на класс `nav` [повесить](https://getbootstrap.com/docs/4.5/components/navs/#vertical) так же клас `flex-column`, а вы свой велосипед изобретаете (даже не хочу разбираться, как вы это сделали). С `navbar` попробуй то же самое: на `navbar-nav` повесь `flex-column`

2020-10-10 09:35 UTC, MrFang commented on core/static/css/core.css
> +  color: #fff;
Угу. А кода в стилях становится больше, и это отвлекает от важной информации

2020-10-10 11:54 UTC, MrFang approved these changes

2020-10-11 11:58 UTC, PitKoro commented
думаю можно мержить

2020-10-11 14:07 UTC, merged

2020-10-11 14:30 UTC, MrFang commented
> думаю можно мержить
> 

Я с Серёгой говорил. Он не был уверен в этом