История транзакций
MrFang/budget-manager pull request #26
Opened 2020-10-19 14:27 UTC by PitKoro

Серверная часть почти готова, осталось добавить кнопку удаления транзакции. Над стилями пока не особо работал.

2020-10-20 07:29 UTC, MrFang commented
Убери алерты. Лучше создай свой класс и стилизуй похожим образом. Пользователю не нужно знать, о нашей внутренней системе транзакций (приход, уход, внутрення), либо ставь знак перед суммой, либо красть в разные цвета. Ещё ты выводишь сумму в копейках, а не рублях. И проверь, пожалуйста, мы не планировали форму выбора периода?

2020-10-20 07:47 UTC, MrFang commented
И да, у меня с меню всё нормально. Это то, почему я топлю за готовый бутстрап, а не велосипеды. Он предсказуемей (но не предсказуемо) ведёт себя на мониторах разной ширины

2020-10-21 15:07 UTC, MrFang requested changes

2020-10-21 15:07 UTC, MrFang commented on core/views.py
> +        el.amount/=100
Не мутируй транзакции!!! Поменяй только вывод в темплейте

2020-10-28 08:10 UTC, MrFang requested changes

2020-10-28 08:10 UTC, MrFang commented on core/templates/core/history.html
> +                    <option value="9">Сентябрь</option>
Почему странный порядок месяцев. Сделай обычный

2020-10-28 08:10 UTC, MrFang commented on core/views.py
> +        if int(filter_value) in [1,2,3,4,5,6,7,8,9,10,11,12]:
Функцию range для кого придумали?

2020-10-28 09:07 UTC, PitKoro commented on core/views.py
> +        if int(filter_value) in [1,2,3,4,5,6,7,8,9,10,11,12]:
Реально

2020-10-30 12:32 UTC, MrFang approved these changes

2020-10-30 12:33 UTC, merged