Design visualisation on main page
MrFang/budget-manager pull request #41
Opened 2020-11-05 15:08 UTC by sergiyvl

2020-11-06 07:51 UTC, MrFang requested changes

2020-11-06 07:51 UTC, MrFang commented on core/static/js/main.js
> +    let chart = new google.visualization.PieChart(document.getElementById('expenses'));
Почему сменил id? Он там специально не простой

2020-11-06 07:51 UTC, MrFang commented on core/utils.py
> +    for cat in ExpenseCategory.objects.all():
У тебя здесь два запроса к базе. Один на все объекты, другой с фильтром. Я уверен, что оба тебе не нужны. И используй `date__range`

2020-11-06 07:51 UTC, MrFang commented on core/views.py
> +from .utils import get_balance, post_income_transaction, post_expense_transaction, get_expenses
Убери, там специально есть импорт всех `utils`

2020-11-06 07:54 UTC, MrFang commented
Надпись No Data всё ещё существует

2020-11-09 09:49 UTC, sergiyvl commented on core/utils.py
> +    for cat in ExpenseCategory.objects.all():
один запрос к ExpenceCATEGORY, другой к ExpenseTRANSACTIONS
1)Можно, конечно, извлекать категории из  ExpenseTRANSACTIONS 
2)Можно сделать проход for transaction in ExpenseTransaction.objects.filter(date__range=[month_date, date_to]): и там извелкать из каждой transaction категорию и все вручную суммировать
но, по-моему, ныне реализованный вариант лучше
или думаешь иначе?

2020-11-09 09:49 UTC, sergiyvl commented on core/views.py
> +from .utils import get_balance, post_income_transaction, post_expense_transaction, get_expenses
ок

2020-11-09 09:50 UTC, sergiyvl commented on core/static/js/main.js
> +    let chart = new google.visualization.PieChart(document.getElementById('expenses'));
ок

2020-11-09 09:53 UTC, MrFang commented on core/utils.py
> +    for cat in ExpenseCategory.objects.all():
Сори, не увидел, что разные таблицы. Вопросов больше не имею

2020-11-09 09:53 UTC, merged